### ISSUE TITLE
The skill is not operating instantly after I power up the Picroft and RPI.

### ISSUE THREAD

**Issue by causpaus** [smolino/picroft_skill_gpio4s#1]
Thanks for creating skills sir. It helps a lot. i just want to ask if the skill is instantly operate after powering the picroft and RPI. Because after powering the picroft and 4-relay module the LED indicators in are just light up and I try to command like ' Turn light on' it seems working in RPI but i think it's not synchronizing in switching in the relay. When I try to command 'Turn light off' still the LED indicators are just light up. I try to run the GPIO.py file and the switching now working in relay. But when I try to turn off the RPI and turn on  it back but still it back it default state.
My goal in my project after I power the picroft and RPI, the home automation instantly work also. Please help me sir to meet this goal. Thanks a lot.

**Comment by smolino** [comment]
Hi causpaus,
I think you may enable i2c
run 
raspi-config
select Interfacing Option
select I2c and enable it
after that switch RPI off / sometimes I had to disconnect AC power and restart RPI

Double check RPI pin connected gpio27, gpio17, gpio22, gpio05 as shown in the image 4relay_bb.png
let me know if that works
Ciao

**Comment by causpaus** [comment]
Thanks sir. The command and switching are now synchronize but one thing I concern. When I powering the RPI and Picroft, the LED indicators lights up. I'm afraid when i connected it to the lights and appliances, and power the RPI and Picroft -  the lights, lamp and other appliances will Turn On automatically and I need to turn off them first to operate home -automation. I hope you get it. Thanks for helping.

**Comment by smolino** [comment]
No problem,
You are right, all  the relays start as soon as the skills as loaded, I did it as load check so I know everything is working.
Anyway I have a look to the code to modify that, and I'll let you know
Ciao

**Comment by causpaus** [comment]
Thanks in advance sir for the help.
